<div align = "center">

# Web Scrapping Module

[![Zenith Clown](https://img.shields.io/badge/👨‍💻-Source_Code-blue)](https://gist.github.com/ZenithClown/809642277fba2d8d2309e55ab307615f)
[![Zenith Clown](https://img.shields.io/badge/📜-Code_Documentation-blue)](https://ds-gringotts.readthedocs.io/en/latest/index.html)

</div>

In [1]:
import pandas as pd
import tablescraper as ts

## Wikipedia Tables

In [2]:
tables = ts.wikitable(weburl = "https://en.wikipedia.org/wiki/List_of_cities_in_India_by_population", verbose = True)
tables[0].sample(3)

Sucessfully Connected to https://en.wikipedia.org/wiki/List_of_cities_in_India_by_population
Fetched 2 from the Wikipedia page.
  >> Converting to Data Frames...

,City,Population (2011)[3],Population (2001)[3][a],State or union territory,Ref
16,Visakhapatnam,1728128,1345938,Andhra Pradesh,[3][b]
5,Chennai,4646732,4343645,Tamil Nadu,[3]
27,Kalyan-Dombivli,1247327,1193512,Maharashtra,[3]

## Chittorgarh Website

In [3]:
table = ts.chittorgarh(
    weburl = "https://www.chittorgarh.com/report/ipo-in-india-list-main-board-sme/82/mainboard/",
    parsedates = True, datecolumns = ["OpeningDate", "ClosingDate", "ListingDate"],
    columns = ["CompanyName", "OpeningDate", "ClosingDate", "ListingDate", "ListingExchange"], dropindex = 0,
    dropcols = ["Issue Price (Rs.)▲▼", "Total Issue Amount (Incl.Firm reservations) (Rs.cr.)▲▼", "Lead Manager▲▼", "Compare"]
)
table.sample(3)

Waiting for Contents...:   0%|          | 0/5 [00:00<?, ?it/s]

,CompanyName,OpeningDate,ClosingDate,ListingDate,ListingExchange
13,Highway Infrastructure Ltd. IPO,2025-08-05,2025-08-07,2025-08-12,"BSE, NSE"
50,Standard Glass Lining Technology Ltd. IPO,2025-01-06,2025-01-08,2025-01-13,"NSE, BSE"
3,Vikran Engineering Ltd. IPO,2025-08-26,2025-08-29,NaT,"BSE, NSE"